import { MigrationInterface, QueryRunner } from "typeorm";

export class Baseline1791466570504 implements MigrationInterface {
    name = 'Baseline1791466570504'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "module" character varying NOT NULL, "action" character varying NOT NULL, "description" character varying, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_017943867ed5ceef9c03edd974" ON "permissions" ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b634526cdd01f2adba6c7ac07" ON "permissions" ("module") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, "isSystem" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_881f72bac969d9a00a1a29e107" ON "roles" ("slug") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fullName" character varying NOT NULL, "email" character varying NOT NULL, "mobile" character varying, "passwordHash" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "twoFactorSecret" character varying, "twoFactorEnabled" boolean NOT NULL DEFAULT false, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "roleId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_368e146b785b574f42ae9e53d5" ON "users" ("roleId") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "tokenHash" character varying NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actorId" uuid, "actorType" character varying NOT NULL DEFAULT 'user', "action" character varying NOT NULL, "entity" character varying, "entityId" character varying, "ipAddress" character varying, "userAgent" character varying, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2dc33f7f3c22e2e7badafca1d1" ON "audit_logs" ("actorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2643f2a68c662985433dbddca1" ON "audit_logs" ("entity", "entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."guardians_howheard_enum" AS ENUM('POPUP', 'ENQUIRY', 'WEBSITE', 'REFERRAL', 'SOCIAL_MEDIA', 'SCHOOL', 'EMAIL_SMS', 'TV_RADIO', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "guardians" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "fullName" character varying NOT NULL, "relationship" character varying, "email" character varying NOT NULL, "secondaryEmail" character varying, "secondaryEmailName" character varying(120), "mobile" character varying NOT NULL, "passwordHash" character varying, "mustChangePassword" boolean NOT NULL DEFAULT false, "tempPasswordExpiresAt" TIMESTAMP WITH TIME ZONE, "credentialsSentAt" TIMESTAMP WITH TIME ZONE, "lastLoginAt" TIMESTAMP WITH TIME ZONE, "emirate" character varying, "city" character varying, "howHeard" "public"."guardians_howheard_enum", "marketingConsent" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "siblingRankOverride" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3dcf02f3dc96a2c017106f280be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_05098ad3ac39996e25e3113494" ON "guardians" ("reference") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2822ea52513239fdd508c016e3" ON "guardians" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdf383e7691c1878d38c65c890" ON "guardians" ("mobile") `);
        await queryRunner.query(`CREATE TYPE "public"."players_gender_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TYPE "public"."players_status_enum" AS ENUM('TRIAL', 'WAITLISTED', 'REGISTERED', 'ACTIVE', 'INACTIVE', 'WITHDRAWN')`);
        await queryRunner.query(`CREATE TYPE "public"."players_level_enum" AS ENUM('DEVELOPMENT', 'ADVANCED', 'HPC')`);
        await queryRunner.query(`CREATE TABLE "players" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "guardianId" uuid NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "gender" "public"."players_gender_enum" NOT NULL, "dateOfBirth" date NOT NULL, "email" character varying, "mobile" character varying, "status" "public"."players_status_enum" NOT NULL DEFAULT 'TRIAL', "ageGroupId" uuid, "ageGroupOverride" boolean NOT NULL DEFAULT false, "level" "public"."players_level_enum", "archivedAt" TIMESTAMP WITH TIME ZONE, "archiveReason" text, "currentTeamId" uuid, "kitSize" character varying, "previousAcademy" character varying, "emergencyContactName" character varying, "emergencyContactPhone" character varying, "medicalNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de22b8fdeee0c33ab55ae71da3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_43482f9f1b265013b746f54294" ON "players" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b5109d23b08c8e0401965b39d" ON "players" ("guardianId") `);
        await queryRunner.query(`CREATE INDEX "IDX_700cf655cdc220804f4b6e1c9b" ON "players" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7bee37783116760bda3b60699" ON "players" ("ageGroupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4eb2854f4526838f8f2d642e1d" ON "players" ("currentTeamId") `);
        await queryRunner.query(`CREATE TABLE "player_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "playerId" uuid NOT NULL, "authorId" uuid, "body" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1c9acc3c2b8f02df60c3509a8fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f25252225da4d270e0eda99d9a" ON "player_comments" ("playerId") `);
        await queryRunner.query(`CREATE TYPE "public"."coaches_employmenttype_enum" AS ENUM('FULL_TIME', 'PART_TIME')`);
        await queryRunner.query(`CREATE TABLE "coaches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "certification" character varying, "bio" text, "employmentType" "public"."coaches_employmenttype_enum", "photoUrl" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_aff053106aac14fb7a780800bc" UNIQUE ("userId"), CONSTRAINT "PK_eddaece1a1f1b197fa39e6864a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_aff053106aac14fb7a780800bc" ON "coaches" ("userId") `);
        await queryRunner.query(`CREATE TABLE "seasons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "startDate" date, "endDate" date, "cutoffDate" date, "isActive" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cb8ed53b5fe109dcd4a4449ec9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_72fcc25659fefafe9afc816844" ON "seasons" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."terms_type_enum" AS ENUM('TERM', 'CAMP', 'EVENT', 'LEAGUE')`);
        await queryRunner.query(`CREATE TABLE "terms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seasonId" uuid NOT NULL, "name" character varying NOT NULL, "type" "public"."terms_type_enum" NOT NULL DEFAULT 'TERM', "startDate" date, "endDate" date, "weeks" integer, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_33b6fe77d6ace7ff43cc8a65958" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4c8d6b9599955fd967fce53e6" ON "terms" ("seasonId") `);
        await queryRunner.query(`CREATE TABLE "locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "emirate" character varying NOT NULL DEFAULT 'Abu Dhabi', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_227023051ab1fedef7a3b6c7e2" ON "locations" ("name") `);
        await queryRunner.query(`CREATE TABLE "venues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "locationId" uuid NOT NULL, "name" character varying NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cb0f885278d12384eb7a81818be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b29977c93f992464724d669153" ON "venues" ("locationId") `);
        await queryRunner.query(`CREATE TABLE "age_groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "minBirthYear" integer, "maxBirthYear" integer, "level" character varying, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_74553a8c46fc414046f0fd02c70" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f31211ca046d2a7ed4bf1bcb36" ON "age_groups" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6c0554ad33a4e9d07e3d3936bd" ON "age_groups" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."teams_level_enum" AS ENUM('DEVELOPMENT', 'ADVANCED', 'HPC')`);
        await queryRunner.query(`CREATE TYPE "public"."teams_squad_enum" AS ENUM('WHITE', 'BLUE')`);
        await queryRunner.query(`CREATE TYPE "public"."teams_trainingdays_enum" AS ENUM('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN')`);
        await queryRunner.query(`CREATE TABLE "teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "seasonId" uuid, "ageGroupId" uuid, "locationId" uuid, "headCoachId" uuid, "capacity" integer NOT NULL DEFAULT '20', "level" "public"."teams_level_enum" NOT NULL DEFAULT 'DEVELOPMENT', "squad" "public"."teams_squad_enum", "squadNumber" integer, "ageCodes" text array NOT NULL DEFAULT '{}', "trainingDays" "public"."teams_trainingdays_enum" array NOT NULL DEFAULT '{}', "startTime" TIME, "endTime" TIME, "girlsOnly" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7e5523774a38b08a6236d322403" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4799a592e7632e2182521dfd3" ON "teams" ("seasonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99bb2cc4d0b21ca2028740d055" ON "teams" ("ageGroupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d924bdcbc233dd2819e640ef42" ON "teams" ("level") `);
        await queryRunner.query(`CREATE TYPE "public"."fees_programtype_enum" AS ENUM('TERM', 'CAMP', 'EVENT', 'LEAGUE')`);
        await queryRunner.query(`CREATE TABLE "fees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "termId" uuid NOT NULL, "ageGroupId" uuid, "locationId" uuid, "level" character varying, "amount" numeric(10,2) NOT NULL, "vatRate" numeric(5,2) NOT NULL DEFAULT '5', "programType" "public"."fees_programtype_enum" NOT NULL DEFAULT 'TERM', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_97f3a1b1b8ee5674fd4da93f461" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c64a00694f9f08dc84a2f6133" ON "fees" ("termId") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_type_enum" AS ENUM('STANDARD', 'LEAGUE', 'CAMP', 'ADDITIONAL', 'CUSTOM')`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'ISSUED', 'PART_PAID', 'PAID', 'REFUNDED', 'WRITTEN_OFF', 'CANCELLED', 'SPONSORED')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "number" character varying NOT NULL, "guardianId" uuid NOT NULL, "type" "public"."invoices_type_enum" NOT NULL DEFAULT 'STANDARD', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'DRAFT', "issueDate" date, "dueDate" date, "subtotal" numeric(10,2) NOT NULL DEFAULT '0', "discountTotal" numeric(10,2) NOT NULL DEFAULT '0', "vatTotal" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL DEFAULT '0', "amountPaid" numeric(10,2) NOT NULL DEFAULT '0', "amountRefunded" numeric(10,2) NOT NULL DEFAULT '0', "writeOffAmount" numeric(10,2) NOT NULL DEFAULT '0', "writeOffReason" character varying, "isSponsored" boolean NOT NULL DEFAULT false, "installments" integer NOT NULL DEFAULT '1', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6b20aa66f2a835a4f2fbde4872" ON "invoices" ("number") `);
        await queryRunner.query(`CREATE INDEX "IDX_16d3f0cff151cce99e89f605db" ON "invoices" ("guardianId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."invoice_line_items_stream_enum" AS ENUM('ACADEMY', 'KITS', 'MAN_CITY_LEAGUE', 'ABU_DHABI_CUP', 'RAMADAN_CUP', 'SALOU_CUP', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "invoice_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "playerId" uuid, "description" character varying NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unitAmount" numeric(10,2) NOT NULL, "vatRate" numeric(5,2) NOT NULL DEFAULT '5', "lineTotal" numeric(10,2) NOT NULL, "stream" "public"."invoice_line_items_stream_enum" NOT NULL DEFAULT 'ACADEMY', "productId" uuid, "kitItems" jsonb, "package" character varying(8), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4e8ccaadaf5d0619db9d219b061" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ec8b1cda36ed79a7ded49bd91" ON "invoice_line_items" ("invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9790e384da732c143b7accf6a0" ON "invoice_line_items" ("stream") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_direction_enum" AS ENUM('INBOUND', 'REFUND')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('CASH', 'CHEQUE', 'CARD', 'BANK_TRANSFER', 'ONLINE', 'WALLET')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "direction" "public"."payments_direction_enum" NOT NULL DEFAULT 'INBOUND', "amount" numeric(10,2) NOT NULL, "method" "public"."payments_method_enum" NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'COMPLETED', "reference" character varying, "gatewayId" character varying, "merchantId" uuid, "merchantName" character varying, "merchantNumber" character varying, "paidAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "recordedById" character varying, "notes" character varying, "instalmentSeq" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_43d19956aeab008b49e0804c14" ON "payments" ("invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE TABLE "invoice_instalments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "seq" integer NOT NULL, "percent" numeric(5,2) NOT NULL, "amount" numeric(10,2) NOT NULL, "dueDate" date NOT NULL, "flag" character varying(8) NOT NULL DEFAULT 'NONE', "waivedAmount" numeric(10,2) NOT NULL DEFAULT '0', "waivedReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aca501c577105158b6c2ba98d6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_74fd9899b65d84c991171e47a8" ON "invoice_instalments" ("invoiceId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_029ce4751e6b21fb50e5a82ba6" ON "invoice_instalments" ("invoiceId", "seq") `);
        await queryRunner.query(`CREATE TABLE "payment_links" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying(64) NOT NULL, "invoiceId" uuid NOT NULL, "instalmentSeq" integer, "amount" numeric(10,2) NOT NULL, "status" character varying(10) NOT NULL DEFAULT 'ACTIVE', "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdById" character varying, "sentAt" TIMESTAMP WITH TIME ZONE, "sentTo" character varying, "openedAt" TIMESTAMP WITH TIME ZONE, "paidAt" TIMESTAMP WITH TIME ZONE, "gatewayId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b176ff8200166713c53d6c3ada" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ae28e08aca9172ee5b822bf83b" ON "payment_links" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_447d2047e1ebdcee622afb06ad" ON "payment_links" ("invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6017bc6a86a04f35e63c6895e8" ON "payment_links" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."discounts_kind_enum" AS ENUM('PERCENTAGE', 'FIXED')`);
        await queryRunner.query(`CREATE TYPE "public"."discounts_rule_enum" AS ENUM('MANUAL', 'SIBLING', 'RETURNING', 'EARLY_BIRD', 'PROMO', 'SPONSOR')`);
        await queryRunner.query(`CREATE TABLE "discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "kind" "public"."discounts_kind_enum" NOT NULL DEFAULT 'PERCENTAGE', "value" numeric(10,2) NOT NULL, "rule" "public"."discounts_rule_enum" NOT NULL DEFAULT 'MANUAL', "params" jsonb, "isActive" boolean NOT NULL DEFAULT true, "isAutomatic" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_66c522004212dc814d6e2f14ecc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."applied_discounts_rule_enum" AS ENUM('MANUAL', 'SIBLING', 'RETURNING', 'EARLY_BIRD', 'PROMO', 'SPONSOR')`);
        await queryRunner.query(`CREATE TABLE "applied_discounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoiceId" uuid NOT NULL, "discountId" uuid, "playerId" uuid, "label" character varying NOT NULL, "rule" "public"."applied_discounts_rule_enum" NOT NULL DEFAULT 'MANUAL', "amount" numeric(10,2) NOT NULL, "wasAutomatic" boolean NOT NULL DEFAULT true, "reason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afa2410d1614d437e9380cf0fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee1bed2d11142cdb581fa422ae" ON "applied_discounts" ("invoiceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9e87e484dc5f4a51a3d11b5b8" ON "applied_discounts" ("playerId") `);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "guardianId" uuid NOT NULL, "balance" numeric(10,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_c52e401b4aea2fe07dd2e6b6f6" UNIQUE ("guardianId"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c52e401b4aea2fe07dd2e6b6f6" ON "wallets" ("guardianId") `);
        await queryRunner.query(`CREATE TYPE "public"."wallet_transactions_type_enum" AS ENUM('CREDIT', 'DEBIT')`);
        await queryRunner.query(`CREATE TABLE "wallet_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "walletId" uuid NOT NULL, "type" "public"."wallet_transactions_type_enum" NOT NULL, "amount" numeric(10,2) NOT NULL, "reason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5120f131bde2cda940ec1a621db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8a94d9d61a2b05123710b325fb" ON "wallet_transactions" ("walletId") `);
        await queryRunner.query(`CREATE TABLE "sibling_credits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "guardianId" character varying NOT NULL, "playerId" uuid NOT NULL, "termId" character varying NOT NULL, "invoiceId" character varying NOT NULL, "triggeredByInvoiceId" character varying NOT NULL, "percentBefore" integer NOT NULL, "percentAfter" integer NOT NULL, "netAmount" numeric(10,2) NOT NULL, "vatAmount" numeric(10,2) NOT NULL, "totalAmount" numeric(10,2) NOT NULL, "appliedToInvoice" numeric(10,2) NOT NULL DEFAULT '0', "reason" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6f07566bbbca46e0d0284af21e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_faaa396d9d6c8111384814f68c" ON "sibling_credits" ("guardianId") `);
        await queryRunner.query(`CREATE INDEX "IDX_88a2fad7f15506538ae97649d2" ON "sibling_credits" ("playerId", "termId") `);
        await queryRunner.query(`CREATE TABLE "price_list" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seasonId" uuid NOT NULL, "sessionsPerWeek" integer NOT NULL, "category" character varying NOT NULL, "sessionRate" numeric(10,2), "prices" jsonb NOT NULL, "vatRate" numeric(5,2) NOT NULL DEFAULT '5', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_52ea7826468b1c889cb2c28df03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f8625b674077977060ef31eab6" ON "price_list" ("seasonId", "sessionsPerWeek", "category") `);
        await queryRunner.query(`CREATE TYPE "public"."products_stream_enum" AS ENUM('ACADEMY', 'KITS', 'MAN_CITY_LEAGUE', 'ABU_DHABI_CUP', 'RAMADAN_CUP', 'SALOU_CUP', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."products_levels_enum" AS ENUM('DEVELOPMENT', 'ADVANCED', 'HPC')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "stream" "public"."products_stream_enum" NOT NULL DEFAULT 'OTHER', "priceInclVat" numeric(10,2) NOT NULL, "vatRate" numeric(5,2) NOT NULL DEFAULT '5', "levels" "public"."products_levels_enum" array NOT NULL DEFAULT '{}', "kitItems" jsonb NOT NULL DEFAULT '[]', "offerAtRegistration" boolean NOT NULL DEFAULT false, "sortOrder" integer NOT NULL DEFAULT '100', "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7cfc24d6c24f0ec91294003d6b" ON "products" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."academy_events_kind_enum" AS ENUM('PITCH_BOOKING', 'MATCH', 'TOURNAMENT', 'EVENT', 'HOLIDAY', 'CAMP')`);
        await queryRunner.query(`CREATE TABLE "academy_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "seasonId" uuid, "kind" "public"."academy_events_kind_enum" NOT NULL, "title" character varying NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "locationId" uuid, "notes" text, "noTraining" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_66d363a1a8712e779e35d4ed2e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_98c3db2f85b0c120922fa0c604" ON "academy_events" ("seasonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c98c9c49b25c9f29073761496a" ON "academy_events" ("startDate") `);
        await queryRunner.query(`CREATE TYPE "public"."merchants_methods_enum" AS ENUM('CASH', 'CHEQUE', 'CARD', 'BANK_TRANSFER', 'ONLINE', 'WALLET')`);
        await queryRunner.query(`CREATE TABLE "merchants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "merchantNumber" character varying NOT NULL, "methods" "public"."merchants_methods_enum" array NOT NULL DEFAULT '{}', "locationId" uuid, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4fd312ef25f8e05ad47bfe7ed25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f125672f13f9d234c6696db220" ON "merchants" ("name") `);
        await queryRunner.query(`CREATE TABLE "app_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" jsonb NOT NULL, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4800b266ba790931744b3e53a74" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_975c2db59c65c05fd9c6b63a2a" ON "app_settings" ("key") `);
        await queryRunner.query(`CREATE TYPE "public"."leads_source_enum" AS ENUM('POPUP', 'ENQUIRY', 'WEBSITE', 'REFERRAL', 'SOCIAL_MEDIA', 'SCHOOL', 'EMAIL_SMS', 'TV_RADIO', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."leads_status_enum" AS ENUM('NEW', 'CONTACTED', 'TRIAL_BOOKED', 'TRIAL_ATTENDED', 'OFFER_MADE', 'REGISTERED', 'LOST')`);
        await queryRunner.query(`CREATE TABLE "leads" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "reference" character varying NOT NULL, "guardianName" character varying NOT NULL, "guardianEmail" character varying, "guardianMobile" character varying NOT NULL, "playerName" character varying NOT NULL, "playerDob" date, "ageGroupLabel" character varying, "level" character varying, "source" "public"."leads_source_enum" NOT NULL DEFAULT 'ENQUIRY', "status" "public"."leads_status_enum" NOT NULL DEFAULT 'NEW', "trialDate" TIMESTAMP WITH TIME ZONE, "venueLabel" character varying, "interested" boolean NOT NULL DEFAULT true, "assignedToId" character varying, "notes" text, "playerId" uuid, "isGuardian" boolean NOT NULL DEFAULT false, "playerGender" character varying(8), "trialTeamId" uuid, "trialSessionId" uuid, "trialOutcome" character varying(16), "trialType" character varying(12), "trialConfirmed" boolean NOT NULL DEFAULT false, "trialCoachId" uuid, "trialEvaluation" character varying(12), "followUpOutcome" character varying(200), "trialFeedback" text, "nextFollowUpAt" TIMESTAMP WITH TIME ZONE, "lastContactedAt" TIMESTAMP WITH TIME ZONE, "contactAttempts" integer NOT NULL DEFAULT '0', "lostReason" character varying, "duplicateOfLeadId" uuid, "existingGuardianId" uuid, "sourceDetail" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_0b54ea5a2106760ed8b6397501" UNIQUE ("playerId"), CONSTRAINT "PK_cd102ed7a9a4ca7d4d8bfeba406" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fc8fd472470762482f5e5eeebf" ON "leads" ("reference") `);
        await queryRunner.query(`CREATE INDEX "IDX_b65118404b3b0f8898ddf0c9ee" ON "leads" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_491b018d616822bd64ce7d4726" ON "leads" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_55e8e375e8cd7650748581bfe7" ON "leads" ("nextFollowUpAt") `);
        await queryRunner.query(`CREATE TABLE "lead_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leadId" uuid NOT NULL, "type" character varying(20) NOT NULL, "body" text, "meta" jsonb, "authorId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1aa1cc6988a817368568ca26bf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e9bae3444c9d4f23c8b8e4aa69" ON "lead_activities" ("leadId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d2dd40d46ac3beb422a05ff9ca" ON "lead_activities" ("type") `);
        await queryRunner.query(`CREATE TABLE "lead_evaluations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "leadId" uuid NOT NULL, "authorId" uuid, "coachId" uuid, "recommendation" character varying(12) NOT NULL, "ratings" jsonb, "strengths" text, "toImprove" text, "recommendedTeamId" uuid, "anotherTrial" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1cd3e71a753842c40653a91e9cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b27e09cb9682632d2ff7bf5e04" ON "lead_evaluations" ("leadId") `);
        await queryRunner.query(`CREATE TYPE "public"."enrolments_status_enum" AS ENUM('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'TRANSFERRED')`);
        await queryRunner.query(`CREATE TABLE "enrolments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "playerId" uuid NOT NULL, "seasonId" uuid NOT NULL, "termId" uuid NOT NULL, "teamId" uuid, "status" "public"."enrolments_status_enum" NOT NULL DEFAULT 'PENDING', "enrolledAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "endedAt" TIMESTAMP WITH TIME ZONE, "sessionsPerWeek" integer, "package" character varying(8), "startDate" date, "invoiceId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6e79971fbd26967c4da9ed52770" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_90982591e018e32faaa54ae838" ON "enrolments" ("playerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9028ffd85f721be9f872c2129c" ON "enrolments" ("seasonId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3eece89ef7ef765bb4de554b3" ON "enrolments" ("termId") `);
        await queryRunner.query(`CREATE INDEX "IDX_da9c7d4ced4bbd947773fa762f" ON "enrolments" ("teamId") `);
        await queryRunner.query(`CREATE TYPE "public"."sessions_type_enum" AS ENUM('TRAINING', 'MATCH', 'TRIAL', 'CAMP', 'EVENT')`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying, "type" "public"."sessions_type_enum" NOT NULL DEFAULT 'TRAINING', "termId" uuid, "teamId" uuid, "locationId" uuid, "venueId" uuid, "coachId" uuid, "startsAt" TIMESTAMP WITH TIME ZONE NOT NULL, "endsAt" TIMESTAMP WITH TIME ZONE NOT NULL, "isCancelled" boolean NOT NULL DEFAULT false, "cancelReason" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d0a9c3f909486a7314899c11e6" ON "sessions" ("teamId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b084b6e5cc26bfe9ecc202391d" ON "sessions" ("startsAt") `);
        await queryRunner.query(`CREATE TYPE "public"."attendances_status_enum" AS ENUM('PRESENT', 'ABSENT', 'EXCUSED', 'LATE')`);
        await queryRunner.query(`CREATE TABLE "attendances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "playerId" uuid NOT NULL, "status" "public"."attendances_status_enum" NOT NULL DEFAULT 'PRESENT', "reason" character varying, "comment" character varying, "recordedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_779f08bc3b89597d6f0b4ee3807" UNIQUE ("sessionId", "playerId"), CONSTRAINT "PK_483ed97cd4cd43ab4a117516b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ceb6790545a68f3cd9d883322f" ON "attendances" ("playerId") `);
        await queryRunner.query(`CREATE TABLE "evaluations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "playerId" uuid NOT NULL, "termId" uuid, "coachId" uuid, "evaluatorId" uuid, "isCustom" boolean NOT NULL DEFAULT false, "scores" jsonb, "notes" text, "reportType" character varying(12), "seasonId" uuid, "teamId" uuid, "status" character varying(10) NOT NULL DEFAULT 'DRAFT', "comments" jsonb, "positions" jsonb, "position" character varying(12), "shirtNumber" integer, "photo" text, "finalizedAt" TIMESTAMP WITH TIME ZONE, "finalizedById" uuid, "sentAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f683b433eba0e6dae7e19b29e29" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e03e1eaa39cc5939f2b1be160" ON "evaluations" ("playerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0b50b4d99a326dcaa34a5817f9" ON "evaluations" ("reportType") `);
        await queryRunner.query(`CREATE INDEX "IDX_9eb25ae21890f3a3017ae59b95" ON "evaluations" ("teamId") `);
        await queryRunner.query(`CREATE TYPE "public"."documents_type_enum" AS ENUM('PHOTO', 'MEDICAL_INSURANCE', 'EMIRATES_ID_FRONT', 'EMIRATES_ID_BACK', 'BIRTH_CERTIFICATE', 'PASSPORT', 'CONSENT_FORM', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."documents_type_enum" NOT NULL, "fileName" character varying NOT NULL, "storageKey" character varying NOT NULL, "mimeType" character varying, "sizeBytes" integer, "expiresAt" TIMESTAMP WITH TIME ZONE, "playerId" uuid, "guardianId" uuid, "uploadedById" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac51aa5181ee2036f5ca482857c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66f0789287cc73ca31dcefd5e4" ON "documents" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd773d5f30b415fdbf6337b185" ON "documents" ("playerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_eb9a537e7259b9c6e249381972" ON "documents" ("guardianId") `);
        await queryRunner.query(`CREATE TYPE "public"."communication_templates_channel_enum" AS ENUM('EMAIL', 'SMS', 'WHATSAPP', 'PUSH')`);
        await queryRunner.query(`CREATE TABLE "communication_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "channel" "public"."communication_templates_channel_enum" NOT NULL, "subject" character varying, "body" text NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca5cd6c5ee3127e345e9d30a719" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4d0688eac5e8a496dff9a553d7" ON "communication_templates" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."communications_channel_enum" AS ENUM('EMAIL', 'SMS', 'WHATSAPP', 'PUSH')`);
        await queryRunner.query(`CREATE TYPE "public"."communications_status_enum" AS ENUM('QUEUED', 'SENT', 'DELIVERED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "communications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channel" "public"."communications_channel_enum" NOT NULL, "status" "public"."communications_status_enum" NOT NULL DEFAULT 'QUEUED', "templateId" uuid, "guardianId" uuid, "toAddress" character varying NOT NULL, "subject" character varying, "body" text NOT NULL, "sentAt" TIMESTAMP WITH TIME ZONE, "error" character varying, "kind" character varying, "attachments" jsonb, "simulated" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_29ec793018d5d5ca19d40149e87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_621757b9213a8abb1f540e62b7" ON "communications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_cbbe49f5049d18290d7b5c6af3" ON "communications" ("guardianId") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_items_programme_enum" AS ENUM('LALIGA', 'ADSC')`);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sku" character varying NOT NULL, "itemCode" character varying NOT NULL, "name" character varying NOT NULL, "programme" "public"."inventory_items_programme_enum" NOT NULL DEFAULT 'LALIGA', "category" character varying NOT NULL, "size" character varying, "unit" character varying NOT NULL DEFAULT 'Pcs', "condition" character varying NOT NULL DEFAULT 'New', "currentStock" integer NOT NULL DEFAULT '0', "minLevel" integer, "location" character varying, "notes" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_395ec8d9e0cad6e3890b989fc1" ON "inventory_items" ("sku") `);
        await queryRunner.query(`CREATE INDEX "IDX_85b0b98a83bbb345c1c90a710a" ON "inventory_items" ("itemCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_9996f955ff3e062c9f3bc241d8" ON "inventory_items" ("programme") `);
        await queryRunner.query(`CREATE INDEX "IDX_618160c99dc65fdd5cc5e384d7" ON "inventory_items" ("category") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_movements_type_enum" AS ENUM('OPENING', 'IN', 'OUT', 'ADJUST')`);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "itemId" uuid NOT NULL, "type" "public"."inventory_movements_type_enum" NOT NULL, "quantity" integer NOT NULL, "balanceAfter" integer NOT NULL, "movedOn" date NOT NULL, "party" character varying, "reason" character varying, "reference" character varying, "playerId" uuid, "batch" character varying, "recordedById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b2f90622bd792e95e1b51dd1ae" ON "inventory_movements" ("itemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8dc70213a51af3ec36b6690dba" ON "inventory_movements" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_9aff3294248f66d565bc9df5c3" ON "inventory_movements" ("movedOn") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c00f9d17b5f65e808c9d58c35" ON "inventory_movements" ("batch") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("rolesId" uuid NOT NULL, "permissionsId" uuid NOT NULL, CONSTRAINT "PK_7931614007a93423204b4b73240" PRIMARY KEY ("rolesId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0cb93c5877d37e954e2aa59e52" ON "role_permissions" ("rolesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d422dabc78ff74a8dab6583da0" ON "role_permissions" ("permissionsId") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_4b5109d23b08c8e0401965b39d9" FOREIGN KEY ("guardianId") REFERENCES "guardians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_f7bee37783116760bda3b606990" FOREIGN KEY ("ageGroupId") REFERENCES "age_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "players" ADD CONSTRAINT "FK_4eb2854f4526838f8f2d642e1d9" FOREIGN KEY ("currentTeamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_comments" ADD CONSTRAINT "FK_f25252225da4d270e0eda99d9af" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player_comments" ADD CONSTRAINT "FK_8758b6394e0e596eb489200d7ed" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coaches" ADD CONSTRAINT "FK_aff053106aac14fb7a780800bce" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terms" ADD CONSTRAINT "FK_b4c8d6b9599955fd967fce53e6d" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "venues" ADD CONSTRAINT "FK_b29977c93f992464724d6691531" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_c4799a592e7632e2182521dfd35" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_99bb2cc4d0b21ca2028740d0558" FOREIGN KEY ("ageGroupId") REFERENCES "age_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_a04c93da4eef2a38de6c015c7ed" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_c9017a7464c3b24b70f4c7429c3" FOREIGN KEY ("headCoachId") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_8c64a00694f9f08dc84a2f61332" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_345b4c7c1622ef696f197bfb8e0" FOREIGN KEY ("ageGroupId") REFERENCES "age_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fees" ADD CONSTRAINT "FK_800992d2c116aee93bf18c9cb48" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_16d3f0cff151cce99e89f605db4" FOREIGN KEY ("guardianId") REFERENCES "guardians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "FK_2ec8b1cda36ed79a7ded49bd913" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "FK_46b7ad4f2daed6ae78bd21278b7" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_43d19956aeab008b49e0804c145" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_instalments" ADD CONSTRAINT "FK_74fd9899b65d84c991171e47a85" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_links" ADD CONSTRAINT "FK_447d2047e1ebdcee622afb06ad1" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applied_discounts" ADD CONSTRAINT "FK_ee1bed2d11142cdb581fa422ae5" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applied_discounts" ADD CONSTRAINT "FK_91022262894d393e3623bc84a6f" FOREIGN KEY ("discountId") REFERENCES "discounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applied_discounts" ADD CONSTRAINT "FK_c9e87e484dc5f4a51a3d11b5b80" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_c52e401b4aea2fe07dd2e6b6f61" FOREIGN KEY ("guardianId") REFERENCES "guardians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" ADD CONSTRAINT "FK_8a94d9d61a2b05123710b325fbf" FOREIGN KEY ("walletId") REFERENCES "wallets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sibling_credits" ADD CONSTRAINT "FK_dfddc375cfa8a7f964e2f815285" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_list" ADD CONSTRAINT "FK_d1eb4ffdc8c84834d5bd0671a2b" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academy_events" ADD CONSTRAINT "FK_ca7cc6ab84619888f9bea11f94d" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_0b54ea5a2106760ed8b6397501d" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_activities" ADD CONSTRAINT "FK_e9bae3444c9d4f23c8b8e4aa69a" FOREIGN KEY ("leadId") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead_evaluations" ADD CONSTRAINT "FK_b27e09cb9682632d2ff7bf5e04b" FOREIGN KEY ("leadId") REFERENCES "leads"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrolments" ADD CONSTRAINT "FK_90982591e018e32faaa54ae8381" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrolments" ADD CONSTRAINT "FK_9028ffd85f721be9f872c2129c4" FOREIGN KEY ("seasonId") REFERENCES "seasons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrolments" ADD CONSTRAINT "FK_f3eece89ef7ef765bb4de554b3a" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrolments" ADD CONSTRAINT "FK_da9c7d4ced4bbd947773fa762fe" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enrolments" ADD CONSTRAINT "FK_ed4d7aa37a19987672a10459917" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_c8aee2268365431216e58dc0ceb" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_d0a9c3f909486a7314899c11e69" FOREIGN KEY ("teamId") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_ead0ed8b23d0617b5f11904967a" FOREIGN KEY ("locationId") REFERENCES "locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_0978abed1ad5792554fdb75467d" FOREIGN KEY ("venueId") REFERENCES "venues"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_05cd6e3a432882da4cde90b6ed1" FOREIGN KEY ("coachId") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_d5140a0a7ab7511a8d326eef004" FOREIGN KEY ("sessionId") REFERENCES "sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD CONSTRAINT "FK_ceb6790545a68f3cd9d883322f2" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_0e03e1eaa39cc5939f2b1be160b" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_feea2232f3d89e2027be93c068f" FOREIGN KEY ("termId") REFERENCES "terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_c7c7f8c946c4fc93c60adbbba8a" FOREIGN KEY ("coachId") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evaluations" ADD CONSTRAINT "FK_d9bc0902066eeac8d46a333efad" FOREIGN KEY ("evaluatorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_fd773d5f30b415fdbf6337b1856" FOREIGN KEY ("playerId") REFERENCES "players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "documents" ADD CONSTRAINT "FK_eb9a537e7259b9c6e2493819724" FOREIGN KEY ("guardianId") REFERENCES "guardians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communications" ADD CONSTRAINT "FK_c13e72d62b47936a1488c4c5801" FOREIGN KEY ("templateId") REFERENCES "communication_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "communications" ADD CONSTRAINT "FK_cbbe49f5049d18290d7b5c6af35" FOREIGN KEY ("guardianId") REFERENCES "guardians"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_b2f90622bd792e95e1b51dd1ae7" FOREIGN KEY ("itemId") REFERENCES "inventory_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_d422dabc78ff74a8dab6583da02" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_d422dabc78ff74a8dab6583da02"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_b2f90622bd792e95e1b51dd1ae7"`);
        await queryRunner.query(`ALTER TABLE "communications" DROP CONSTRAINT "FK_cbbe49f5049d18290d7b5c6af35"`);
        await queryRunner.query(`ALTER TABLE "communications" DROP CONSTRAINT "FK_c13e72d62b47936a1488c4c5801"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_eb9a537e7259b9c6e2493819724"`);
        await queryRunner.query(`ALTER TABLE "documents" DROP CONSTRAINT "FK_fd773d5f30b415fdbf6337b1856"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_d9bc0902066eeac8d46a333efad"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_c7c7f8c946c4fc93c60adbbba8a"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_feea2232f3d89e2027be93c068f"`);
        await queryRunner.query(`ALTER TABLE "evaluations" DROP CONSTRAINT "FK_0e03e1eaa39cc5939f2b1be160b"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_ceb6790545a68f3cd9d883322f2"`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP CONSTRAINT "FK_d5140a0a7ab7511a8d326eef004"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_05cd6e3a432882da4cde90b6ed1"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_0978abed1ad5792554fdb75467d"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_ead0ed8b23d0617b5f11904967a"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_d0a9c3f909486a7314899c11e69"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_c8aee2268365431216e58dc0ceb"`);
        await queryRunner.query(`ALTER TABLE "enrolments" DROP CONSTRAINT "FK_ed4d7aa37a19987672a10459917"`);
        await queryRunner.query(`ALTER TABLE "enrolments" DROP CONSTRAINT "FK_da9c7d4ced4bbd947773fa762fe"`);
        await queryRunner.query(`ALTER TABLE "enrolments" DROP CONSTRAINT "FK_f3eece89ef7ef765bb4de554b3a"`);
        await queryRunner.query(`ALTER TABLE "enrolments" DROP CONSTRAINT "FK_9028ffd85f721be9f872c2129c4"`);
        await queryRunner.query(`ALTER TABLE "enrolments" DROP CONSTRAINT "FK_90982591e018e32faaa54ae8381"`);
        await queryRunner.query(`ALTER TABLE "lead_evaluations" DROP CONSTRAINT "FK_b27e09cb9682632d2ff7bf5e04b"`);
        await queryRunner.query(`ALTER TABLE "lead_activities" DROP CONSTRAINT "FK_e9bae3444c9d4f23c8b8e4aa69a"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_0b54ea5a2106760ed8b6397501d"`);
        await queryRunner.query(`ALTER TABLE "academy_events" DROP CONSTRAINT "FK_ca7cc6ab84619888f9bea11f94d"`);
        await queryRunner.query(`ALTER TABLE "price_list" DROP CONSTRAINT "FK_d1eb4ffdc8c84834d5bd0671a2b"`);
        await queryRunner.query(`ALTER TABLE "sibling_credits" DROP CONSTRAINT "FK_dfddc375cfa8a7f964e2f815285"`);
        await queryRunner.query(`ALTER TABLE "wallet_transactions" DROP CONSTRAINT "FK_8a94d9d61a2b05123710b325fbf"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_c52e401b4aea2fe07dd2e6b6f61"`);
        await queryRunner.query(`ALTER TABLE "applied_discounts" DROP CONSTRAINT "FK_c9e87e484dc5f4a51a3d11b5b80"`);
        await queryRunner.query(`ALTER TABLE "applied_discounts" DROP CONSTRAINT "FK_91022262894d393e3623bc84a6f"`);
        await queryRunner.query(`ALTER TABLE "applied_discounts" DROP CONSTRAINT "FK_ee1bed2d11142cdb581fa422ae5"`);
        await queryRunner.query(`ALTER TABLE "payment_links" DROP CONSTRAINT "FK_447d2047e1ebdcee622afb06ad1"`);
        await queryRunner.query(`ALTER TABLE "invoice_instalments" DROP CONSTRAINT "FK_74fd9899b65d84c991171e47a85"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_43d19956aeab008b49e0804c145"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "FK_46b7ad4f2daed6ae78bd21278b7"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "FK_2ec8b1cda36ed79a7ded49bd913"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_16d3f0cff151cce99e89f605db4"`);
        await queryRunner.query(`ALTER TABLE "fees" DROP CONSTRAINT "FK_800992d2c116aee93bf18c9cb48"`);
        await queryRunner.query(`ALTER TABLE "fees" DROP CONSTRAINT "FK_345b4c7c1622ef696f197bfb8e0"`);
        await queryRunner.query(`ALTER TABLE "fees" DROP CONSTRAINT "FK_8c64a00694f9f08dc84a2f61332"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_c9017a7464c3b24b70f4c7429c3"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_a04c93da4eef2a38de6c015c7ed"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_99bb2cc4d0b21ca2028740d0558"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_c4799a592e7632e2182521dfd35"`);
        await queryRunner.query(`ALTER TABLE "venues" DROP CONSTRAINT "FK_b29977c93f992464724d6691531"`);
        await queryRunner.query(`ALTER TABLE "terms" DROP CONSTRAINT "FK_b4c8d6b9599955fd967fce53e6d"`);
        await queryRunner.query(`ALTER TABLE "coaches" DROP CONSTRAINT "FK_aff053106aac14fb7a780800bce"`);
        await queryRunner.query(`ALTER TABLE "player_comments" DROP CONSTRAINT "FK_8758b6394e0e596eb489200d7ed"`);
        await queryRunner.query(`ALTER TABLE "player_comments" DROP CONSTRAINT "FK_f25252225da4d270e0eda99d9af"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_4eb2854f4526838f8f2d642e1d9"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_f7bee37783116760bda3b606990"`);
        await queryRunner.query(`ALTER TABLE "players" DROP CONSTRAINT "FK_4b5109d23b08c8e0401965b39d9"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d422dabc78ff74a8dab6583da0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cb93c5877d37e954e2aa59e52"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c00f9d17b5f65e808c9d58c35"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9aff3294248f66d565bc9df5c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dc70213a51af3ec36b6690dba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2f90622bd792e95e1b51dd1ae"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_618160c99dc65fdd5cc5e384d7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9996f955ff3e062c9f3bc241d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85b0b98a83bbb345c1c90a710a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_395ec8d9e0cad6e3890b989fc1"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_items_programme_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbbe49f5049d18290d7b5c6af3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_621757b9213a8abb1f540e62b7"`);
        await queryRunner.query(`DROP TABLE "communications"`);
        await queryRunner.query(`DROP TYPE "public"."communications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."communications_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d0688eac5e8a496dff9a553d7"`);
        await queryRunner.query(`DROP TABLE "communication_templates"`);
        await queryRunner.query(`DROP TYPE "public"."communication_templates_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb9a537e7259b9c6e249381972"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd773d5f30b415fdbf6337b185"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66f0789287cc73ca31dcefd5e4"`);
        await queryRunner.query(`DROP TABLE "documents"`);
        await queryRunner.query(`DROP TYPE "public"."documents_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9eb25ae21890f3a3017ae59b95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b50b4d99a326dcaa34a5817f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e03e1eaa39cc5939f2b1be160"`);
        await queryRunner.query(`DROP TABLE "evaluations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ceb6790545a68f3cd9d883322f"`);
        await queryRunner.query(`DROP TABLE "attendances"`);
        await queryRunner.query(`DROP TYPE "public"."attendances_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b084b6e5cc26bfe9ecc202391d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0a9c3f909486a7314899c11e6"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TYPE "public"."sessions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da9c7d4ced4bbd947773fa762f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3eece89ef7ef765bb4de554b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9028ffd85f721be9f872c2129c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90982591e018e32faaa54ae838"`);
        await queryRunner.query(`DROP TABLE "enrolments"`);
        await queryRunner.query(`DROP TYPE "public"."enrolments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b27e09cb9682632d2ff7bf5e04"`);
        await queryRunner.query(`DROP TABLE "lead_evaluations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2dd40d46ac3beb422a05ff9ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9bae3444c9d4f23c8b8e4aa69"`);
        await queryRunner.query(`DROP TABLE "lead_activities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55e8e375e8cd7650748581bfe7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_491b018d616822bd64ce7d4726"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b65118404b3b0f8898ddf0c9ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc8fd472470762482f5e5eeebf"`);
        await queryRunner.query(`DROP TABLE "leads"`);
        await queryRunner.query(`DROP TYPE "public"."leads_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."leads_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_975c2db59c65c05fd9c6b63a2a"`);
        await queryRunner.query(`DROP TABLE "app_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f125672f13f9d234c6696db220"`);
        await queryRunner.query(`DROP TABLE "merchants"`);
        await queryRunner.query(`DROP TYPE "public"."merchants_methods_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c98c9c49b25c9f29073761496a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98c3db2f85b0c120922fa0c604"`);
        await queryRunner.query(`DROP TABLE "academy_events"`);
        await queryRunner.query(`DROP TYPE "public"."academy_events_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7cfc24d6c24f0ec91294003d6b"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_levels_enum"`);
        await queryRunner.query(`DROP TYPE "public"."products_stream_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f8625b674077977060ef31eab6"`);
        await queryRunner.query(`DROP TABLE "price_list"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88a2fad7f15506538ae97649d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_faaa396d9d6c8111384814f68c"`);
        await queryRunner.query(`DROP TABLE "sibling_credits"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a94d9d61a2b05123710b325fb"`);
        await queryRunner.query(`DROP TABLE "wallet_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."wallet_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c52e401b4aea2fe07dd2e6b6f6"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9e87e484dc5f4a51a3d11b5b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee1bed2d11142cdb581fa422ae"`);
        await queryRunner.query(`DROP TABLE "applied_discounts"`);
        await queryRunner.query(`DROP TYPE "public"."applied_discounts_rule_enum"`);
        await queryRunner.query(`DROP TABLE "discounts"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_rule_enum"`);
        await queryRunner.query(`DROP TYPE "public"."discounts_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6017bc6a86a04f35e63c6895e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_447d2047e1ebdcee622afb06ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae28e08aca9172ee5b822bf83b"`);
        await queryRunner.query(`DROP TABLE "payment_links"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_029ce4751e6b21fb50e5a82ba6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74fd9899b65d84c991171e47a8"`);
        await queryRunner.query(`DROP TABLE "invoice_instalments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43d19956aeab008b49e0804c14"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_direction_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9790e384da732c143b7accf6a0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ec8b1cda36ed79a7ded49bd91"`);
        await queryRunner.query(`DROP TABLE "invoice_line_items"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_line_items_stream_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16d3f0cff151cce99e89f605db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b20aa66f2a835a4f2fbde4872"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c64a00694f9f08dc84a2f6133"`);
        await queryRunner.query(`DROP TABLE "fees"`);
        await queryRunner.query(`DROP TYPE "public"."fees_programtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d924bdcbc233dd2819e640ef42"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99bb2cc4d0b21ca2028740d055"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4799a592e7632e2182521dfd3"`);
        await queryRunner.query(`DROP TABLE "teams"`);
        await queryRunner.query(`DROP TYPE "public"."teams_trainingdays_enum"`);
        await queryRunner.query(`DROP TYPE "public"."teams_squad_enum"`);
        await queryRunner.query(`DROP TYPE "public"."teams_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6c0554ad33a4e9d07e3d3936bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f31211ca046d2a7ed4bf1bcb36"`);
        await queryRunner.query(`DROP TABLE "age_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b29977c93f992464724d669153"`);
        await queryRunner.query(`DROP TABLE "venues"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_227023051ab1fedef7a3b6c7e2"`);
        await queryRunner.query(`DROP TABLE "locations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4c8d6b9599955fd967fce53e6"`);
        await queryRunner.query(`DROP TABLE "terms"`);
        await queryRunner.query(`DROP TYPE "public"."terms_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72fcc25659fefafe9afc816844"`);
        await queryRunner.query(`DROP TABLE "seasons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aff053106aac14fb7a780800bc"`);
        await queryRunner.query(`DROP TABLE "coaches"`);
        await queryRunner.query(`DROP TYPE "public"."coaches_employmenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f25252225da4d270e0eda99d9a"`);
        await queryRunner.query(`DROP TABLE "player_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eb2854f4526838f8f2d642e1d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7bee37783116760bda3b60699"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_700cf655cdc220804f4b6e1c9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b5109d23b08c8e0401965b39d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43482f9f1b265013b746f54294"`);
        await queryRunner.query(`DROP TABLE "players"`);
        await queryRunner.query(`DROP TYPE "public"."players_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."players_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."players_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdf383e7691c1878d38c65c890"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2822ea52513239fdd508c016e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05098ad3ac39996e25e3113494"`);
        await queryRunner.query(`DROP TABLE "guardians"`);
        await queryRunner.query(`DROP TYPE "public"."guardians_howheard_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2643f2a68c662985433dbddca1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2dc33f7f3c22e2e7badafca1d1"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_368e146b785b574f42ae9e53d5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_881f72bac969d9a00a1a29e107"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b634526cdd01f2adba6c7ac07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017943867ed5ceef9c03edd974"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
